### ISSUE TITLE
Julie share how she created named files for github tutorial 

### ISSUE THREAD

**Issue by erinmr** [Openscapes/seaside-chats#6]
Share how she created automatic markdown docs for the tutorials in each cohort

**Comment by jules32** [comment]
June 11 2021:

We talked through: 

The beginnings of: https://github.com/Openscapes/openscapesr/blob/main/R/create_gh_demos.R

And saw the old code I ran in each repo, using datapasta rather than googlesheets4:

https://github.com/Openscapes/csu-coast-cohort/commit/a8bc2e534c6d58af4683947f5285e779de6b4303#diff-28f9c8f2cab44ebe472e1c12f6c745d123781cce4b7f671ead533fecc690b5d8
